### ISSUE TITLE
Eror imort tkiner

### ISSUE THREAD

**Issue by ghost** [Desklop/Voice_ChatBot#1]
root@Dell:/home/lavrenkov/Voice_ChatBOt# python3 bot.py train
Traceback (most recent call last):
  File "bot.py", line 8, in <module>
    from preprocessing import Preparation
  File "/home/lavrenkov/Voice_ChatBOt/preprocessing.py", line 11, in <module>
    import matplotlib.pyplot as plt
  File "/usr/local/lib/python3.6/dist-packages/matplotlib/pyplot.py", line 2374, in <module>
    switch_backend(rcParams["backend"])
  File "/usr/local/lib/python3.6/dist-packages/matplotlib/pyplot.py", line 207, in switch_backend
    backend_mod = importlib.import_module(backend_name)
  File "/usr/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/usr/local/lib/python3.6/dist-packages/matplotlib/backends/backend_tkagg.py", line 1, in <module>
    from . import _backend_tk
  File "/usr/local/lib/python3.6/dist-packages/matplotlib/backends/_backend_tk.py", line 5, in <module>
    import tkinter as Tk
ModuleNotFoundError: No module named 'tkinter'

**Comment by ghost** [comment]
how to fix it?
ubuntu 18.04
installation via .sh file

**Comment by ghost** [comment]
To fix the need to install the python3-tk package
