### ISSUE TITLE
RHVoice eror

### ISSUE THREAD

**Issue by ghost** [Desklop/Voice_ChatBot#3]
[i] Выберите вариант работы бота:
	1. train - обучение модели seq2seq
	2. predict - работа с обученной моделью seq2seq
	3. predict -ss - включено озвучивание ответов с помощью RHVoice
	4. predict -sr - включено распознавание речи с помощью PocketSphinx
	5. predict -ss -sr - включено озвучивание ответов и распознавание речи
Введите цифру: 4
[i] Загрузка параметров сети из data/net_model.txt и data/net_final_weights.h5
2018-11-21 19:01:24.488971: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
[i] Инициализация языковой модели...
Traceback (most recent call last):
  File "bot.py", line 239, in <module>
    main()
  File "bot.py", line 218, in main
    predict(True, False)
  File "bot.py", line 136, in predict
    sr = SpeechRecognition('from_microphone')
  File "/home/lavrenkov/Voice_ChatBot/speech_to_text.py", line 45, in __init__
    dic=os.path.join(model_path, 'ru_bot.dic')
  File "/usr/local/lib/python3.6/dist-packages/pocketsphinx/__init__.py", line 208, in __init__
    super(LiveSpeech, self).__init__(**kwargs)
  File "/usr/local/lib/python3.6/dist-packages/pocketsphinx/__init__.py", line 90, in __init__
    super(Pocketsphinx, self).__init__(config)
  File "/usr/local/lib/python3.6/dist-packages/pocketsphinx/pocketsphinx.py", line 273, in __init__
    this = _pocketsphinx.new_Decoder(*args)
RuntimeError: new_Decoder returned -1

**Comment by dbklim** [comment]
Нужно положить акустическую модель в /usr/local/lib/python3.5/dist-packages/pocketsphinx/model. Подробнее про это можно найти в статье на хабре https://habr.com/post/351376/

P.S. Это ошибка не RHVoice, а PocketSphinx.

**Comment by ghost** [comment]
Что делать если Python 3.6
