### ISSUE TITLE
При запуске bot.py predict ошибка с векторами

### ISSUE THREAD

**Issue by GraphGrailAi** [Desklop/Voice_ChatBot#6]
Возинкает ошибка при выборе опции 1: 
ValueError: invalid literal for int() with base 10: 'version
что-то с векторами модели.

`python3 bot.py predict

/home/joo/anaconda3/lib/python3.6/site-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
Using TensorFlow backend.
/home/joo/anaconda3/lib/python3.6/site-packages/smart_open/ssh.py:34: UserWarning: paramiko missing, opening SSH/SCP/SFTP paths will be disabled.  `pip install paramiko` to suppress
  warnings.warn('paramiko missing, opening SSH/SCP/SFTP paths will be disabled.  `pip install paramiko` to suppress')
[i] Выберите набор данных:
	1. plays_ru - набор диалогов из пьес
	2. conversations_ru - набор диалогов из различных произведений
	3. subtitles_ru - набор диалогов из субтитров к 347 сериалам
[W] conversations_ru и subtitles_ru ещё в разработке!
Ваш выбор: 1
[i] Используется набор данных plays_ru
[i] Загрузка параметров модели из data/plays_ru/model_plays_ru.json и data/plays_ru/model_weights_plays_ru.h5
2019-05-12 15:20:13.148420: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
2019-05-12 15:20:13.228519: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:964] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2019-05-12 15:20:13.228865: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1432] Found device 0 with properties: 
name: GeForce GTX 1080 major: 6 minor: 1 memoryClockRate(GHz): 1.7715
pciBusID: 0000:01:00.0
totalMemory: 7.93GiB freeMemory: 6.86GiB
2019-05-12 15:20:13.228881: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1511] Adding visible gpu devices: 0
2019-05-12 15:20:13.426428: I tensorflow/core/common_runtime/gpu/gpu_device.cc:982] Device interconnect StreamExecutor with strength 1 edge matrix:
2019-05-12 15:20:13.426457: I tensorflow/core/common_runtime/gpu/gpu_device.cc:988]      0 
2019-05-12 15:20:13.426463: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1001] 0:   N 
2019-05-12 15:20:13.426600: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1115] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 6609 MB memory) -> physical GPU (device: 0, name: GeForce GTX 1080, pci bus id: 0000:01:00.0, compute capability: 6.1)
[i] Установлена максимальная длина предложения 26 слов(-а)
[i] Загрузка модели word2vec из data/plays_ru/w2v_model_plays_ru.bin...
Traceback (most recent call last):
  File "bot.py", line 259, in <module>
    main()
  File "bot.py", line 202, in main
    predict()
  File "bot.py", line 143, in predict
    ttt = TextToText(f_name_w2v_model=f_name_w2v_model, f_name_model=f_name_model, f_name_model_weights=f_name_model_weights)
  File "/home/joo/Документы/LocalRepository/Voice_ChatBot-master/text_to_text.py", line 74, in __init__
    self.w2v = WordToVec(f_name_w2v_model)
  File "/home/joo/Документы/LocalRepository/Voice_ChatBot-master/word_to_vec.py", line 33, in __init__
    self.model = word2vec.Word2VecKeyedVectors.load_word2vec_format(f_name_w2v_model, binary=True)
  File "/home/joo/anaconda3/lib/python3.6/site-packages/gensim/models/keyedvectors.py", line 1476, in load_word2vec_format
    limit=limit, datatype=datatype)
  File "/home/joo/anaconda3/lib/python3.6/site-packages/gensim/models/utils_any2vec.py", line 344, in _load_word2vec_format
    vocab_size, vector_size = (int(x) for x in header.split())  # throws for invalid file format
  File "/home/joo/anaconda3/lib/python3.6/site-packages/gensim/models/utils_any2vec.py", line 344, in <genexpr>
    vocab_size, vector_size = (int(x) for x in header.split())  # throws for invalid file format
ValueError: invalid literal for int() with base 10: 'version'`

При выборе опции 3 будет другая ошибка:

`  File "/home/joo/Документы/LocalRepository/Voice_ChatBot-master/text_to_text.py", line 230, in __load_model
    with open(f_name_model, 'r') as f_model:
FileNotFoundError: [Errno 2] No such file or directory: 'data/subtitles_ru/model_subtitles_ru.json'
`

**Comment by dbklim** [comment]
Я извиняюсь, что раньше не заметил ваш вопрос. Надеюсь ещё актуально.

Эта ошибка возникла из-за того, что появились ограничения на использование Git LFS (теперь можно загружать не более 1Гб данных, а у меня их больше 3Гб). Но сейчас я обновил репозиторий и теперь всё будет работать :)
